---
- name: Example playbook with loop
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Create multiple directories
      file:
        path: "/tmp/{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - dir1
        - dir2
        - dir3

    - name: Display a message for each directory
      debug:
        msg: "Directory {{ item }} has been created."
      loop:
        - dir1
        - dir2
        - dir3